export const feedUrls = [
  // 'http://httpstat.us/500',
  'https://feeds.a.dj.com/rss/RSSMarketsMain.xml',
  'https://feeds.a.dj.com/rss/WSJcomUSBusiness.xml',
  'https://feeds.a.dj.com/rss/RSSWorldNews.xml',
  'https://feeds.a.dj.com/rss/RSSWSJD.xml',
  'https://rsshub.app/apnews/topics/apf-topnews',
  'http://feeds.latimes.com/latimes/business',
  'http://feeds.latimes.com/latimes/news/nationworld/world',
  'https://rss.nytimes.com/services/xml/rss/nyt/HomePage.xml',
  'https://rss.nytimes.com/services/xml/rss/nyt/Business.xml',
  'https://www.chicagotribune.com/rss2.0.xml',
  'https://www.theguardian.com/us/rss',
  'http://feeds.foxnews.com/foxnews/latest',
  'https://feeds.npr.org/1001/rss.xml',
  'https://feeds.npr.org/1013/rss.xml',
  'https://feeds.npr.org/1032/rss.xml',
  'https://feeds.npr.org/1007/rss.xml',
  'https://www.newsweek.com/rss',
  // 'https://www.youtube.com/feeds/videos.xml?channel_id=UChqUTb7kYRX8-EiaN3XFrSQ',
  'https://rsshub.app/twitter/user/elonmusk/exclude_replies'
];
